'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'id' | 'en'

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('id')

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('rifinity_language') as Language
      if (saved === 'id' || saved === 'en') {
        setLanguageState(saved)
      }
      const savedTheme = localStorage.getItem('rifinity_theme')
      if (savedTheme === 'light') {
        document.documentElement.classList.add('light-mode')
      } else {
        document.documentElement.classList.remove('light-mode')
      }
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('rifinity_language', lang)
      // Dispatch a custom event to notify all components reactively
      window.dispatchEvent(new Event('rifinity_language_change'))
    }
  }

  useEffect(() => {
    const handleStorageChange = () => {
      const saved = localStorage.getItem('rifinity_language') as Language
      if (saved === 'id' || saved === 'en') {
        setLanguageState(saved)
      }
    }
    window.addEventListener('rifinity_language_change', handleStorageChange)
    window.addEventListener('storage', handleStorageChange)
    return () => {
      window.removeEventListener('rifinity_language_change', handleStorageChange)
      window.removeEventListener('storage', handleStorageChange)
    }
  }, [])

  // Dynamic localization dictionary matching Rifinity Logistik's features
  const t = (key: string, fallback?: string): string => {
    const translations: Record<Language, Record<string, string>> = {
      id: {
        'dashboard': 'Dashboard',
        'smart_inbound': 'Inbound Pintar',
        'laporan_inbound': 'Laporan Inbound',
        'smart_outbound': 'Outbound Pintar',
        'laporan_outbound': 'Laporan Outbound',
        'inventory': 'Inventaris',
        'docs_helper': 'Asisten Dokumen',
        'laporan_keuangan': 'Laporan Keuangan',
        'settings': 'Pengaturan',
        'keluar_sistem': 'Keluar dari Sistem',
        'keluar_loading': 'Keluar...',
        'verifikasi_sesi': 'Memverifikasi sesi...',
        // Dashboard
        'overview': 'Ikhtisar',
        'total_items': 'Total Barang',
        'outbound_today': 'Outbound Hari Ini',
        'inbound_today': 'Inbound Hari Ini',
        'critical_items': 'Stok Kritis',
        'predictive_alerts': 'Alert Prediktif',
        'stock_movement': 'Pergerakan Stok Terkini',
        'recent_activities': 'Aktivitas Terbaru',
        'view_all': 'Lihat Semua',
        'need_restock': 'Butuh Restock',
        'low_stock_warning': 'Peringatan Stok Rendah!',
        'create_restock_doc': 'Buat Draf Surat Restock',
        // Settings
        'profil_anda': 'Profil Anda',
        'ai_logistik': 'AI Logistik',
        'sistem': 'Sistem',
        'threshold_wms': 'Threshold WMS',
        'kop_surat_brand': 'Kop Surat & Brand',
        'integrasi_alert': 'Integrasi & Alert',
        'save_configuration': 'Simpan Konfigurasi',
        'saved_successfully': 'Berhasil Disimpan!',
        'system_settings_title': 'Pengaturan Sistem',
        'system_settings_desc': 'Konfigurasikan profil pengguna, mesin AI logistik, dan pengaturan sistem.',
        'pilihan_bahasa': 'Pilihan Bahasa (Language)',
        'pilihan_bahasa_desc': 'Pilih bahasa pengantar antarmuka aplikasi Rifinity Logistik.',
        'tema_tampilan': 'Tema Tampilan (Theme)',
        'tema_tampilan_desc': 'Pilih tema visual antarmuka sistem (Gelap atau Terang).',
        // Financial Reports Page
        'financial_reports_title': 'Laporan Keuangan & Kinerja',
        'financial_reports_desc': 'Analisis laba rugi operasional, perputaran stok, dan nilai aset pergudangan.',
        'total_inbound': 'Total Inbound',
        'total_outbound': 'Total Outbound',
        'daily_average': 'Rata-rata Harian',
        'inventory_turnover': 'Inventory Turnover',
        'units': 'unit',
        'units_per_day': 'unit/hari',
        'per_month': 'per bulan',
        'financial_analysis': 'Analisis Finansial Pergudangan',
        'expense_label': 'Belanja Pengadaan Barang (Expense)',
        'expense_desc': 'Hanya mencakup pembelian barang milik internal PT',
        'income_label': 'Total Pemasukan Operasional (Income)',
        'internal_sales': 'Jual Internal',
        'fulfillment_services': 'Jasa 3PL',
        'net_profit_label': 'Margin Keuntungan Bersih (Laba/Rugi)',
        'status_surplus': '✓ STATUS SURPLUS (LABA OPERASIONAL)',
        'status_deficit': '✗ STATUS DEFISIT (RUGI OPERASIONAL)',
        'warehouse_asset_valuation': 'Nilai Aset Stok Gudang (PT)',
        'warehouse_asset_desc': 'Total nilai modal barang fisik di atas rak',
        'client_asset_valuation': 'Nilai Barang Titipan (Klien 3PL)',
        'client_asset_desc': 'Penting untuk perhitungan asuransi klaim gudang',
        'total_shipping_cost_label': 'Total Ongkos Kirim Logistik',
        'total_shipping_cost_desc': 'Akumulasi biaya pengiriman via ekspedisi',
        'inbound_outbound_trend': 'Tren Inbound vs Outbound (6 Bulan Terakhir)',
        'top_active_items': 'Top Barang Paling Aktif',
        'no_transaction_data': 'Belum ada data transaksi.',
        'transactions': 'transaksi',
        'export_pdf': 'Export PDF',
        // Dashboard Page
        'wcc_title': 'Warehouse Control Center',
        'wcc_subtitle': 'Selamat datang kembali, Petugas Logistik. Berikut status pergudangan Anda.',
        'wcc_loading': 'Memuat data dashboard...',
        'total_expense_month': 'Total Pengeluaran (Bulan Ini)',
        'total_income_month': 'Total Pemasukan (Bulan Ini)',
        'realtime_flow_chart': 'Arus Barang Real-Time (30 Hari Terakhir)',
        'performance_trend_chart': 'Tren Arus Barang Gudang (6 Bulan Terakhir)',
        'inbound_masuk': 'Inbound (Masuk)',
        'outbound_keluar': 'Outbound (Keluar)',
        'predictive_restock_alert': 'Predictive Restock Alert',
        'all_stock_healthy': 'Semua stok dalam kondisi aman atau data tidak tersedia.',
        'only_left': 'Tersisa hanya',
        'order_now': 'Pesan Sekarang',
        'recent_activity': 'Aktivitas Terbaru',
        'no_recent_activity': 'Tidak ada aktivitas terbaru.',
        'received': 'Menerima',
        'dispatched': 'Mengirim',
        'units_of': 'unit dari',
        // Inventory Page
        'inventory_title': 'Inventory',
        'inventory_desc': 'Kelola dan pantau stok barang gudang secara real-time.',
        'add_item': 'Tambah Barang',
        'total_sku': 'Total SKU',
        'critical_stock': 'Stok Kritis',
        'total_units': 'Total Unit',
        'search_placeholder': 'Cari nama barang atau SKU...',
        'table_item_name': 'Nama Barang',
        'table_sku': 'SKU',
        'table_category': 'Kategori',
        'table_owner': 'Pemilik (Owner)',
        'table_stock': 'Stok',
        'table_location': 'Lokasi',
        'table_status': 'Status',
        'table_action': 'Aksi',
        'loading': 'Loading...',
        'internal': 'Internal',
        'status_critical': 'Kritis',
        'status_low': 'Rendah',
        'status_normal': 'Normal',
        'print_label': 'Cetak Label',
        'edit': 'Edit',
        'save': 'Simpan',
        'click_to_change_location': 'Klik untuk ubah lokasi',
        'add_new_item': 'Tambah Barang Baru',
        'item_name_req': 'Nama Barang *',
        'sku_req': 'SKU Barang *',
        'category_req': 'Kategori *',
        'unit_type': 'Satuan Unit',
        'owner_req': 'Pemilik (Owner) *',
        'buy_price_label': 'Harga Beli (Modal)',
        'sell_price_label': 'Harga Jual (Pemasukan)',
        'initial_stock': 'Stok Awal',
        'rack_location': 'Lokasi Rak',
        'warehouse_location': 'Lokasi Gudang',
        'default_supplier': 'Pemasok Default (Supplier)',
        'notes_label': 'Catatan',
        'cancel': 'Batal',
        'adding_loading': 'Menambahkan...',
        'save_item': 'Simpan Barang',

        // Smart Inbound
        'smart_inbound_subtitle': 'Input barang masuk dengan bantuan AI — scan dokumen atau isi manual.',
        'inbound_form_title': 'Data Barang Masuk',
        'qty_and_unit': 'Jumlah & Satuan',
        'buy_price_unit': 'Harga Beli (Satuan)',
        'sell_price_unit': 'Harga Jual (Satuan)',
        'save_inbound': 'Simpan Barang Masuk',
        'ai_doc_reader': 'AI Document Reader',
        'ai_doc_reader_desc': 'Upload foto surat jalan atau dokumen pengiriman — AI akan mengisi form secara otomatis.',
        'click_to_upload_doc': 'Klik untuk upload foto dokumen',
        'doc_types_sub': '(Surat Jalan, Invoice, Packing Slip)',
        'extract_with_ai': 'Extract dengan AI',
        'extract_loading': '🔄 Membaca dokumen...',
        'remove': 'Hapus',
        'recent_inbound': 'Riwayat Inbound Terkini',
        'no_data': 'Belum ada data',
        'preview_rack_barcode': 'Preview Barcode Rak',
        'print_rack_barcode': 'Cetak Barcode Rak',
        'inbound_saved_success': 'Barang masuk berhasil disimpan!',
        'inbound_saved_fail': 'Gagal menyimpan data barang.',
        'inbound_upload_err': 'Silakan upload/pilih gambar dokumen terlebih dahulu!',
        'inbound_extract_success': 'Ekstraksi AI Berhasil!',
        'inbound_extract_fail': 'Gagal mengekstrak dokumen. Pastikan API key Anda aktif.',
        'inbound_ai_success_msg': 'AI berhasil mengekstrak dokumen!',

        // Inbound History (Laporan Inbound)
        'inbound_history_title': 'Laporan Riwayat Inbound',
        'inbound_history_desc': 'Tracking komprehensif, filter terperinci, dan ekspor PDF resmi logistik inbound.',
        'include_pdf_details': 'Sertakan Rincian di PDF',
        'export_pdf_btn': 'Ekspor PDF (Cetak Laporan)',
        'total_inbound_goods': 'Total Barang Masuk',
        'total_available_stock_realtime': 'Total Stok Tersedia (Real-Time)',
        'total_purchase_valuation': 'Total Nilai Pembelian (Valuasi)',
        'total_suppliers': 'Jumlah Supplier',
        'most_active_rack_zone': 'Zona Rak Teraktif',
        'internal_pt': 'Internal PT',
        'client_consignment': 'Titipan Klien',
        'pt_expense_capital': 'Belanja PT (Modal)',
        'client_consigned_assets': 'Aset Titipan Klien',
        'suppliers_count': 'Pemasok',
        'active_partners': 'Mitra Aktif',
        'main_warehouse': 'Gudang Utama',
        'inbound_search_placeholder': 'Cari supplier, lokasi rak, barang, SKU...',
        'all_months': 'Semua Bulan',
        'december': 'Desember',
        'january': 'Januari',
        'february': 'Februari',
        'march': 'Maret',
        'april': 'April',
        'may': 'Mei',
        'all_years': 'Semua Tahun',
        'search': 'Cari',
        'reset': 'Reset',
        'table_time': 'Waktu',
        'table_item_detail': 'Detail Barang',
        'table_quantity': 'Jumlah',
        'table_purchase_value': 'Nilai Pembelian',
        'table_supplier': 'Supplier / Pemasok',
        'table_storage_rack': 'Penyimpanan & Rak',
        'table_notes': 'Catatan',
        'consigned': 'Titipan',
        'ai_chat_title': 'Asisten AI Logistik',
        'ai_chat_placeholder': 'Tanyakan tentang stok, pengiriman...',
        'ai_chat_welcome': 'Halo! Saya asisten logistik AI. Ada yang bisa saya bantu? Misalnya: "Mana barang yang stoknya paling sedikit?" atau "Tolong buka halaman inbound"',
        'ai_chat_error': 'Terjadi kesalahan.',
        'ai_chat_failed': 'Gagal terhubung ke server.',
        'general_vendor': 'Vendor Umum',
        'official_distribution': 'Distribusi Resmi',
        'managed_capacity': 'Kapasitas Terkelola',
        'loading_inbound_history': 'Mengambil riwayat transaksi inbound...',
        'data_not_found': 'Data Tidak Ditemukan',
        'inbound_history_empty_desc': 'Tidak ada riwayat penerimaan IN yang cocok dengan filter yang ditentukan.',
        'official_inbound_report_title': 'Laporan Resmi Penerimaan Barang (Inbound Dispatch Report)',
        'official_wms_ledger_subtitle': 'Sistem WMS Rifinity Logistik — Operational Ledger Audit',
        'print_date': 'Tanggal Cetak',
        'print_section_1': 'I. Metrik Finansial & Operasional',
        'print_section_2': 'II. Ringkasan Volume per Item (Top 8)',
        'print_section_3': 'III. Rincian Ledger Logistik Inbound',

        // Smart Outbound (Packaging)
        'smart_outbound_subtitle': 'Asisten AI untuk optimasi kemasan dan pencatatan barang keluar pergudangan.',
        'tab_dispatch': 'Catat Barang Keluar (OUT)',
        'tab_packaging_assistant': 'Asisten Kemasan AI',
        'dimensions_weight_card': 'Dimensi & Berat Barang',
        'length_cm': 'Panjang (cm)',
        'width_cm': 'Lebar (cm)',
        'height_cm': 'Tinggi (cm)',
        'weight_kg': 'Berat (kg)',
        'recommend_packaging': 'Rekomendasikan Kemasan',
        'analyzing_loading': '🔄 Menganalisis...',
        'ai_recommendation_title': 'Rekomendasi AI',
        'recommended_packaging_sub': 'Kemasan yang Direkomendasikan',
        'reason': 'Alasan',
        'ai_recommendation_empty_tip': 'Isi dimensi dan klik "Rekomendasikan" untuk melihat hasil AI',
        'packaging_history_title': 'Riwayat Rekomendasi Kemasan',
        'table_dimensions': 'Dimensi (cm)',
        'table_weight': 'Berat',
        'table_packaging': 'Kemasan',
        'no_history_data': 'Belum ada data riwayat',
        'outbound_form_title': 'Formulir Pengeluaran Barang (OUT)',
        'select_item': '-- Pilih Barang --',
        'recipient_name': 'Nama Penerima / Pembeli',
        'outbound_qty': 'Kuantitas Keluar',
        'sell_price_unit_rp': 'Harga Jual Satuan (Rp)',
        'address_shipping_title': 'Alamat & Pengiriman',
        'destination_province': '-- Pilih Provinsi --',
        'destination_city': '-- Pilih Kota/Kab --',
        'full_destination_address': 'Alamat Lengkap Tujuan',
        'resi_awb_number': 'Nomor Resi / AWB (Manual/Auto)',
        'resi_placeholder': 'Terisi otomatis jika kosong',
        'available_courier_services': 'Layanan Kurir Tersedia',
        'calculating_shipping_loading': '🔄 Menghitung Ongkos Kirim Lintas Provinsi...',
        'payment_method_label': 'Metode Pembayaran',
        'payment_cash': '💵 Tunai',
        'payment_non_cash': '📲 Non-Tunai (Transfer/QRIS)',
        'additional_shipping_notes': 'Catatan Pengiriman Tambahan (Opsional)',
        'dispatch_outbound_btn': 'Kirim Barang Keluar (OUT)',
        'dispatch_processing_loading': '🔄 Memproses...',
        'details_cost_estimation': 'Rincian & Estimasi Biaya',
        'select_item_estimation_tip': 'Pilih barang di formulir sebelah kiri untuk melihat rincian stok & kepemilikan.',
        'item_name': 'Nama Barang',
        'warehouse_stock': 'Stok Gudang',
        'total_package_weight': 'Total Berat Paket',
        'outbound_value_details': 'Rincian Nilai Outbound:',
        'items_subtotal': 'Subtotal Barang',
        'shipping_fee': 'Ongkos Kirim',
        'total_estimated_transaction': 'Total Estimasi Transaksi:',
        'estimation_real_geographical_tip': 'Estimasi dihitung berdasarkan berat dikali jarak geografis logistik riil.',
        'outbound_dispatch_history_title': 'Riwayat Pengiriman Barang Keluar (OUT)',
        'outbound_search_placeholder': 'Cari penerima, resi, kota, nama barang...',
        'table_outbound_qty': 'Jumlah Keluar',
        'table_item_value': 'Nilai Barang (Rp)',
        'table_expedition_resi_recipient': 'Ekspedisi, Resi & Alamat Penerima',
        'table_label': 'Label',
        'print_btn': 'Cetak',
        'preview_shipping_label': 'Preview Label Pengiriman',
        'receiver_label': 'PENERIMA:',
        'sender_label': 'PENGIRIM:',
        'package_content_label': 'ISI PAKET:',
        'weight_label': 'Berat:',
        'courier_label': 'Kurir:',
        'print_physical_label': 'Cetak Fisik Label',
        'outbound_saved_success': 'Barang keluar berhasil dicatat!',
        'outbound_saved_fail': 'Gagal memproses barang keluar.',
        'outbound_select_err': 'Silakan pilih barang terlebih dahulu!',
        'outbound_qty_err': 'Jumlah barang keluar tidak valid!',
        'outbound_stock_err': 'Stok tidak mencukupi!',
        'outbound_city_err': 'Silakan pilih kota tujuan pengiriman!',
        'outbound_courier_err': 'Silakan pilih kurir pengiriman!',

        // Outbound History (Laporan Outbound)
        'outbound_history_title': 'Laporan Riwayat Outbound',
        'outbound_history_desc': 'Tracking komprehensif, filter terperinci, dan ekspor PDF resmi logistik outbound.',
        'total_packages_sent': 'Total Paket Terkirim',
        'total_distribution_valuation': 'Total Nilai Distribusi (Valuasi)',
        'accumulated_shipping_cost': 'Akumulasi Ongkos Kirim',
        'most_popular_courier': 'Kurir Terpopuler',
        'outbound_history_search_placeholder': 'Cari penerima, resi AWB, barang, kota...',
        'table_item_value_label': 'Nilai Barang',
        'table_recipient_address': 'Penerima / Alamat',
        'table_expedition_cost': 'Ekspedisi & Biaya',
        'loading_outbound_history': 'Mengambil riwayat transaksi outbound...',
        'outbound_history_empty_desc': 'Tidak ada riwayat pengiriman OUT yang cocok dengan filter yang ditentukan.',
        'official_outbound_report_title': 'Laporan Resmi Pengeluaran Barang (Outbound Dispatch Report)',
        'print_section_3_outbound': 'III. Rincian Ledger Logistik Outbound',
        'outbound_print_report_title': 'Laporan Resmi Pengeluaran Barang (Outbound Dispatch Report)',
        'print_system_wms': 'Sistem WMS Rifinity Logistik — Operational Ledger Audit',
        'print_period': 'Periode Laporan',
        'print_sec_1': 'I. Metrik Finansial & Operasional',
        'print_total_outbound_volume': 'Total Volume Outbound',
        'print_internal_owned': 'Milik Internal PT',
        'print_client_consigned': 'Titipan Klien 3PL',
        'print_total_goods_value': 'Total Nilai Barang (Modal/Jual)',
        'print_client_assets': 'Aset Klien 3PL',
        'print_total_shipping_fees': 'Total Ongkos Kirim Logistik',
        'print_most_popular_courier': 'Kurir / Ekspedisi Terpopuler',
        'print_sec_2': 'II. Ringkasan Volume per Item (Top 8)',
        'print_sec_3_outbound': 'III. Rincian Ledger Logistik Outbound',
        'outbound_history_report_title': 'Laporan Riwayat Outbound',
        'outbound_history_report_subtitle': 'Tracking komprehensif, filter terperinci, dan ekspor PDF resmi logistik outbound.',
        'pdf_include_details': 'Sertakan Rincian di PDF',
        'pdf_export_report': 'Ekspor PDF (Cetak Laporan)',
        'total_packages_dispatched': 'Total Paket Terkirim',
        'internal_owned': 'Internal PT',
        'client_consigned': 'Titipan Klien',
        'on_hand_stock': 'Stok Fisik di Rak WMS',
        'total_distribution_value_valuation': 'Total Nilai Distribusi (Valuasi)',
        'total_goods': 'Total Nilai Barang',
        'receipts': 'Resi',
        'search_dispatch_placeholder': 'Cari penerima, resi AWB, barang, kota...',
        'btn_search': 'Cari',
        'btn_reset': 'Reset',
        'empty_outbound_history_alert': 'Tidak ada riwayat pengiriman OUT yang cocok dengan filter yang ditentukan.',
        'category_short': 'Kategori',
        'address_not_written': 'Alamat tidak ditulis',
        'awb_receipt': 'No Resi / AWB',
        'non_cash': 'Non-Tunai',
        'cash': 'Tunai',

        // Docs Helper
        'docs_helper_title': 'Docs Helper',
        'docs_helper_subtitle': 'Tanya AI tentang dokumen perdagangan, regulasi ekspor-impor, dan logistik internasional.',
        'ask_ai_logistics': 'Tanya AI Logistik',
        'ask_ai_placeholder': 'Contoh: "Apa perbedaan FOB dan CIF?"',
        'ai_drafting_answer': 'AI sedang menyusun jawaban...',
        'ai_response_draft_po': 'AI Response Draft PO',
        'download': 'Download',
        'download_docx': 'Download .docx',
        'download_pdf': 'Download .pdf',
        'common_questions': 'Pertanyaan Umum',
        'document_topics': 'Topik Dokumen',
        'loading_docs_helper': 'Loading Docs Helper...',
        'topic_incoterms': 'Incoterms 2020',
        'topic_incoterms_desc': 'FOB, CIF, EXW, DDP dan lainnya',
        'topic_export_docs': 'Dokumen Ekspor',
        'topic_export_docs_desc': 'Invoice, Packing List, B/L, COO',
        'topic_hs_code': 'HS Code',
        'topic_hs_code_desc': 'Harmonized System untuk klasifikasi barang',
        'ai_failed_draft_po': 'Mohon maaf, draf Purchase Order gagal dibuat secara otomatis. Coba ulangi dengan mengetik di kotak saran.',
        'ai_failed_restock': 'Mohon maaf, draf surat permohonan restock gagal dibuat secara otomatis. Coba ulangi dengan mengetik di kotak saran.',
        'ai_failed_system': 'Mohon maaf, sistem AI sedang sibuk atau terjadi kesalahan. Coba lagi nanti.',
        'common_q_1': 'Apa itu Incoterms dan kapan digunakan?',
        'common_q_2': 'Dokumen apa saja yang dibutuhkan untuk ekspor?',
        'common_q_3': 'Bagaimana cara menghitung bea masuk barang impor?',
        'common_q_4': 'Apa perbedaan B/L dan AWB?',
        'common_q_5': 'Cara membaca HS Code untuk tekstil?'
      },
      en: {
        'dashboard': 'Dashboard',
        'smart_inbound': 'Smart Inbound',
        'laporan_inbound': 'Inbound Reports',
        'smart_outbound': 'Smart Outbound',
        'laporan_outbound': 'Outbound Reports',
        'inventory': 'Inventory',
        'docs_helper': 'Docs Helper',
        'laporan_keuangan': 'Financial Reports',
        'settings': 'Settings',
        'keluar_sistem': 'Sign Out',
        'keluar_loading': 'Signing out...',
        'verifikasi_sesi': 'Verifying session...',
        // Dashboard
        'overview': 'Overview',
        'total_items': 'Total Items',
        'outbound_today': 'Outbound Today',
        'inbound_today': 'Inbound Today',
        'critical_items': 'Critical Stock',
        'predictive_alerts': 'Predictive Alerts',
        'stock_movement': 'Recent Stock Movement',
        'recent_activities': 'Recent Activities',
        'view_all': 'View All',
        'need_restock': 'Needs Restock',
        'low_stock_warning': 'Low Stock Warning!',
        'create_restock_doc': 'Draft Restock Letter',
        // Settings
        'profil_anda': 'Your Profile',
        'ai_logistik': 'AI Logistics',
        'sistem': 'System',
        'threshold_wms': 'WMS Thresholds',
        'kop_surat_brand': 'Letterhead & Brand',
        'integrasi_alert': 'Integration & Alert',
        'save_configuration': 'Save Configuration',
        'saved_successfully': 'Saved Successfully!',
        'system_settings_title': 'System Settings',
        'system_settings_desc': 'Configure user profile, AI logistics engine, and application settings.',
        'pilihan_bahasa': 'Language Selection',
        'pilihan_bahasa_desc': 'Choose the language for the Rifinity Logistics interface.',
        'tema_tampilan': 'Theme Selector',
        'tema_tampilan_desc': 'Choose system interface visual theme (Dark or Light).',
        // Financial Reports Page
        'financial_reports_title': 'Financial & Performance Reports',
        'financial_reports_desc': 'Operational profit/loss analysis, stock turnover, and warehouse asset valuation.',
        'total_inbound': 'Total Inbound',
        'total_outbound': 'Total Outbound',
        'daily_average': 'Daily Average',
        'inventory_turnover': 'Inventory Turnover',
        'units': 'units',
        'units_per_day': 'units/day',
        'per_month': 'per month',
        'financial_analysis': 'Warehouse Financial Analysis',
        'expense_label': 'Inventory Procurement (Expense)',
        'expense_desc': 'Only covers internal stock purchases of PT',
        'income_label': 'Total Operational Revenue (Income)',
        'internal_sales': 'Internal Sales',
        'fulfillment_services': '3PL Services',
        'net_profit_label': 'Net Operating Margin (Profit/Loss)',
        'status_surplus': '✓ SURPLUS STATUS (OPERATIONAL PROFIT)',
        'status_deficit': '✗ DEFICIT STATUS (OPERATIONAL LOSS)',
        'warehouse_asset_valuation': 'Warehouse Asset Valuation (PT)',
        'warehouse_asset_desc': 'Total capital value of physical stock on racks',
        'client_asset_valuation': 'Consigned Goods Value (3PL Client)',
        'client_asset_desc': 'Crucial for warehouse claim insurance calculation',
        'total_shipping_cost_label': 'Total Logistics Shipping Cost',
        'total_shipping_cost_desc': 'Accumulated courier dispatch costs',
        'inbound_outbound_trend': 'Inbound vs Outbound Trend (Last 6 Months)',
        'top_active_items': 'Top Most Active Items',
        'no_transaction_data': 'No transaction data available yet.',
        'transactions': 'transactions',
        'export_pdf': 'Export PDF',
        // Dashboard Page
        'wcc_title': 'Warehouse Control Center',
        'wcc_subtitle': "Welcome back, Logistic Officer. Here's your warehouse status.",
        'wcc_loading': 'Loading dashboard data...',
        'total_expense_month': 'Total Expense (This Month)',
        'total_income_month': 'Total Income (This Month)',
        'realtime_flow_chart': 'Real-Time Stock Flow (Last 30 Days)',
        'performance_trend_chart': 'Warehouse Flow Trend (Last 6 Months)',
        'inbound_masuk': 'Inbound (Received)',
        'outbound_keluar': 'Outbound (Dispatched)',
        'predictive_restock_alert': 'Predictive Restock Alert',
        'all_stock_healthy': 'All stock levels are healthy or data unavailable.',
        'only_left': 'Only',
        'order_now': 'Order Now',
        'recent_activity': 'Recent Activity',
        'no_recent_activity': 'No recent activity.',
        'received': 'Received',
        'dispatched': 'Dispatched',
        'units_of': 'units of',
        // Inventory Page
        'inventory_title': 'Inventory',
        'inventory_desc': 'Manage and track warehouse physical stock in real-time.',
        'add_item': 'Add Item',
        'total_sku': 'Total SKUs',
        'critical_stock': 'Critical Stock',
        'total_units': 'Total Units',
        'search_placeholder': 'Search item name or SKU...',
        'table_item_name': 'Item Name',
        'table_sku': 'SKU',
        'table_category': 'Category',
        'table_owner': 'Owner',
        'table_stock': 'Stock',
        'table_location': 'Location',
        'table_status': 'Status',
        'table_action': 'Action',
        'loading': 'Loading...',
        'internal': 'Internal',
        'status_critical': 'Critical',
        'status_low': 'Low',
        'status_normal': 'Normal',
        'print_label': 'Print Label',
        'edit': 'Edit',
        'save': 'Save',
        'click_to_change_location': 'Click to change location',
        'add_new_item': 'Add New Item',
        'item_name_req': 'Item Name *',
        'sku_req': 'SKU *',
        'category_req': 'Category *',
        'unit_type': 'Unit Type',
        'owner_req': 'Owner *',
        'buy_price_label': 'Cost Price',
        'sell_price_label': 'Selling Price',
        'initial_stock': 'Initial Stock',
        'rack_location': 'Rack Location',
        'warehouse_location': 'Warehouse Location',
        'default_supplier': 'Default Supplier',
        'notes_label': 'Notes',
        'cancel': 'Cancel',
        'adding_loading': 'Adding...',
        'save_item': 'Save Item',

        // Smart Inbound
        'smart_inbound_subtitle': 'Input inbound goods with AI assistance — scan document or fill manually.',
        'inbound_form_title': 'Inbound Goods Data',
        'qty_and_unit': 'Quantity & Unit',
        'buy_price_unit': 'Cost Price (Per Unit)',
        'sell_price_unit': 'Selling Price (Per Unit)',
        'save_inbound': 'Save Inbound Goods',
        'ai_doc_reader': 'AI Document Reader',
        'ai_doc_reader_desc': 'Upload shipping slip or delivery document photo — AI will auto-fill the form.',
        'click_to_upload_doc': 'Click to upload document photo',
        'doc_types_sub': '(Delivery Slip, Invoice, Packing Slip)',
        'extract_with_ai': 'Extract with AI',
        'extract_loading': '🔄 Reading document...',
        'remove': 'Remove',
        'recent_inbound': 'Recent Inbound Logs',
        'no_data': 'No data available',
        'preview_rack_barcode': 'Preview Rack Barcode',
        'print_rack_barcode': 'Print Rack Barcode',
        'inbound_saved_success': 'Inbound goods successfully saved!',
        'inbound_saved_fail': 'Failed to save inbound goods data.',
        'inbound_upload_err': 'Please upload/select document image first!',
        'inbound_extract_success': 'AI Extraction Successful!',
        'inbound_extract_fail': 'Failed to extract document. Make sure your API key is active.',
        'inbound_ai_success_msg': 'AI successfully extracted document!',

        // Inbound History (Laporan Inbound)
        'inbound_history_title': 'Inbound History Reports',
        'inbound_history_desc': 'Comprehensive tracking, granular filters, and official exportable inbound logs PDF.',
        'include_pdf_details': 'Include Details in PDF',
        'export_pdf_btn': 'Export PDF (Print Report)',
        'total_inbound_goods': 'Total Inbound Goods',
        'total_available_stock_realtime': 'Total Stock Available (Real-Time)',
        'total_purchase_valuation': 'Total Purchase Value (Valuation)',
        'total_suppliers': 'Total Suppliers',
        'most_active_rack_zone': 'Most Active Rack Zone',
        'internal_pt': 'PT Internal',
        'client_consignment': 'Client Consigned',
        'pt_expense_capital': 'PT Expense (Capital)',
        'client_consigned_assets': 'Client Consigned Assets',
        'suppliers_count': 'Suppliers',
        'active_partners': 'Active Partners',
        'main_warehouse': 'Main Warehouse',
        'inbound_search_placeholder': 'Search supplier, rack location, item, SKU...',
        'all_months': 'All Months',
        'december': 'December',
        'january': 'January',
        'february': 'February',
        'march': 'March',
        'april': 'April',
        'may': 'May',
        'all_years': 'All Years',
        'search': 'Search',
        'reset': 'Reset',
        'table_time': 'Time',
        'table_item_detail': 'Item Detail',
        'table_quantity': 'Quantity',
        'table_purchase_value': 'Purchase Value',
        'table_supplier': 'Supplier / Vendor',
        'table_storage_rack': 'Storage & Rack',
        'table_notes': 'Notes',
        'consigned': 'Consigned',
        'ai_chat_title': 'Logistic AI Assistant',
        'ai_chat_placeholder': 'Ask about stock, shipping...',
        'ai_chat_welcome': 'Hello! I am your AI logistics assistant. How can I help you? For example: "Which item has the lowest stock?" or "Please open the inbound page"',
        'ai_chat_error': 'An error occurred.',
        'ai_chat_failed': 'Failed to connect to the server.',
        'general_vendor': 'General Vendor',
        'official_distribution': 'Official Distribution',
        'managed_capacity': 'Managed Capacity',
        'loading_inbound_history': 'Fetching inbound transaction history...',
        'data_not_found': 'No Data Found',
        'inbound_history_empty_desc': 'No inbound reception logs match the specified filters.',
        'official_inbound_report_title': 'Official Inbound Goods Report (Inbound Dispatch Report)',
        'official_wms_ledger_subtitle': 'Rifinity Logistics WMS System — Operational Ledger Audit',
        'print_date': 'Print Date',
        'print_section_1': 'I. Financial & Operational Metrics',
        'print_section_2': 'II. Volume Summary per Item (Top 8)',
        'print_section_3': 'III. Detailed Inbound Logistics Ledger',

        // Smart Outbound (Packaging)
        'smart_outbound_subtitle': 'AI assistant for packaging optimization and outbound warehousing records.',
        'tab_dispatch': 'Dispatch Outbound Goods (OUT)',
        'tab_packaging_assistant': 'AI Packaging Assistant',
        'dimensions_weight_card': 'Item Dimensions & Weight',
        'length_cm': 'Length (cm)',
        'width_cm': 'Width (cm)',
        'height_cm': 'Height (cm)',
        'weight_kg': 'Weight (kg)',
        'recommend_packaging': 'Recommend Packaging',
        'analyzing_loading': '🔄 Analyzing...',
        'ai_recommendation_title': 'AI Recommendation',
        'recommended_packaging_sub': 'Recommended Packaging Type',
        'reason': 'Reason',
        'ai_recommendation_empty_tip': 'Enter dimensions and click "Recommend" to see AI analysis',
        'packaging_history_title': 'Packaging Recommendation History',
        'table_dimensions': 'Dimensions (cm)',
        'table_weight': 'Weight',
        'table_packaging': 'Packaging',
        'no_history_data': 'No history data available',
        'outbound_form_title': 'Outbound Dispatch Form (OUT)',
        'select_item': '-- Select Item --',
        'recipient_name': 'Recipient / Buyer Name',
        'outbound_qty': 'Outbound Quantity',
        'sell_price_unit_rp': 'Unit Selling Price (Rp)',
        'address_shipping_title': 'Address & Shipping Dispatch',
        'destination_province': '-- Select Province --',
        'destination_city': '-- Select City --',
        'full_destination_address': 'Full Destination Address',
        'resi_awb_number': 'AWB Tracking Number (Manual/Auto)',
        'resi_placeholder': 'Auto-generated if left empty',
        'available_courier_services': 'Available Courier Services',
        'calculating_shipping_loading': '🔄 Calculating Inter-Province Shipping Cost...',
        'payment_method_label': 'Payment Method',
        'payment_cash': '💵 Cash',
        'payment_non_cash': '📲 Non-Cash (Transfer/QRIS)',
        'additional_shipping_notes': 'Additional Shipping Notes (Optional)',
        'dispatch_outbound_btn': 'Dispatch Outbound (OUT)',
        'dispatch_processing_loading': '🔄 Processing...',
        'details_cost_estimation': 'Details & Cost Estimation',
        'select_item_estimation_tip': 'Select an item in the form to view stock levels and ownership details.',
        'item_name': 'Item Name',
        'warehouse_stock': 'Warehouse Stock',
        'total_package_weight': 'Total Package Weight',
        'outbound_value_details': 'Outbound Transaction Details:',
        'items_subtotal': 'Items Subtotal',
        'shipping_fee': 'Shipping Cost',
        'total_estimated_transaction': 'Total Estimated Transaction:',
        'estimation_real_geographical_tip': 'Estimates are based on package weight multiplied by real logistics distance.',
        'outbound_dispatch_history_title': 'Outbound Dispatch History logs (OUT)',
        'outbound_search_placeholder': 'Search recipient, tracking, city, item name...',
        'table_outbound_qty': 'Outbound Qty',
        'table_item_value': 'Goods Value (Rp)',
        'table_expedition_resi_recipient': 'Expedition, Tracking AWB & Recipient Address',
        'table_label': 'Label',
        'print_btn': 'Print',
        'preview_shipping_label': 'Preview Shipping Label',
        'receiver_label': 'TO:',
        'sender_label': 'FROM:',
        'package_content_label': 'PACKAGE CONTENT:',
        'weight_label': 'Weight:',
        'courier_label': 'Courier:',
        'print_physical_label': 'Print Shipping Label',
        'outbound_saved_success': 'Outbound dispatch successfully recorded!',
        'outbound_saved_fail': 'Failed to process outbound dispatch.',
        'outbound_select_err': 'Please select an item first!',
        'outbound_qty_err': 'Invalid outbound quantity!',
        'outbound_stock_err': 'Insufficient warehouse stock!',
        'outbound_city_err': 'Please select a destination city!',
        'outbound_courier_err': 'Please select a delivery courier!',

        // Outbound History (Laporan Outbound)
        'outbound_history_title': 'Outbound History Reports',
        'outbound_history_desc': 'Comprehensive tracking, granular filters, and official exportable outbound logs PDF.',
        'total_packages_sent': 'Total Packages Sent',
        'total_distribution_valuation': 'Total Distribution Value (Valuation)',
        'accumulated_shipping_cost': 'Accumulated Shipping Cost',
        'most_popular_courier': 'Most Popular Courier',
        'outbound_history_search_placeholder': 'Search recipient, tracking AWB, item, city...',
        'table_item_value_label': 'Goods Value',
        'table_recipient_address': 'Recipient / Address',
        'table_expedition_cost': 'Expedition & Costs',
        'loading_outbound_history': 'Fetching outbound transaction history...',
        'outbound_history_empty_desc': 'No outbound dispatch logs match the specified filters.',
        'official_outbound_report_title': 'Official Outbound Dispatch Report (Outbound Dispatch Report)',
        'print_section_3_outbound': 'III. Detailed Outbound Logistics Ledger',
        'outbound_print_report_title': 'Official Outbound Dispatch Report (Outbound Dispatch Report)',
        'print_system_wms': 'Rifinity Logistics WMS System — Operational Ledger Audit',
        'print_period': 'Report Period',
        'print_sec_1': 'I. Financial & Operational Metrics',
        'print_total_outbound_volume': 'Total Outbound Volume',
        'print_internal_owned': 'PT Internal Owned',
        'print_client_consigned': '3PL Client Consigned',
        'print_total_goods_value': 'Total Goods Value (Cost/Sell)',
        'print_client_assets': '3PL Client Assets',
        'print_total_shipping_fees': 'Total Logistics Shipping Cost',
        'print_most_popular_courier': 'Most Popular Courier / Expedition',
        'print_sec_2': 'II. Volume Summary per Item (Top 8)',
        'print_sec_3_outbound': 'III. Detailed Outbound Logistics Ledger',
        'outbound_history_report_title': 'Outbound History Reports',
        'outbound_history_report_subtitle': 'Comprehensive tracking, granular filters, and official exportable outbound logs PDF.',
        'pdf_include_details': 'Include Details in PDF',
        'pdf_export_report': 'Export PDF (Print Report)',
        'total_packages_dispatched': 'Total Packages Sent',
        'internal_owned': 'PT Internal',
        'client_consigned': 'Client Consigned',
        'on_hand_stock': 'Physical Stock on WMS Racks',
        'total_distribution_value_valuation': 'Total Distribution Value (Valuation)',
        'total_goods': 'Total Goods Value',
        'receipts': 'Receipts',
        'search_dispatch_placeholder': 'Search recipient, tracking AWB, item, city...',
        'btn_search': 'Search',
        'btn_reset': 'Reset',
        'empty_outbound_history_alert': 'No outbound dispatch logs match the specified filters.',
        'category_short': 'Category',
        'address_not_written': 'Address not written',
        'awb_receipt': 'No Tracking / AWB',
        'non_cash': 'Non-Cash',
        'cash': 'Cash',

        // Docs Helper
        'docs_helper_title': 'Docs Helper',
        'docs_helper_subtitle': 'Ask AI about commercial documents, export-import regulations, and international logistics.',
        'ask_ai_logistics': 'Ask AI Logistics',
        'ask_ai_placeholder': 'Example: "What is the difference between FOB and CIF?"',
        'ai_drafting_answer': 'AI is drafting response...',
        'ai_response_draft_po': 'AI Response Draft PO',
        'download': 'Download',
        'download_docx': 'Download .docx',
        'download_pdf': 'Download .pdf',
        'common_questions': 'Common Questions',
        'document_topics': 'Document Topics',
        'loading_docs_helper': 'Loading Docs Helper...',
        'topic_incoterms': 'Incoterms 2020',
        'topic_incoterms_desc': 'FOB, CIF, EXW, DDP and more',
        'topic_export_docs': 'Export Documents',
        'topic_export_docs_desc': 'Invoice, Packing List, B/L, COO',
        'topic_hs_code': 'HS Code',
        'topic_hs_code_desc': 'Harmonized System for goods classification',
        'ai_failed_draft_po': 'Sorry, the draft Purchase Order could not be automatically generated. Please try again by typing in the suggestion box.',
        'ai_failed_restock': 'Sorry, the draft restock request letter could not be automatically generated. Please try again by typing in the suggestion box.',
        'ai_failed_system': 'Sorry, the AI system is busy or an error occurred. Please try again later.',
        'common_q_1': 'What are Incoterms and when are they used?',
        'common_q_2': 'What documents are required for export?',
        'common_q_3': 'How to calculate import customs duty?',
        'common_q_4': 'What is the difference between B/L and AWB?',
        'common_q_5': 'How to read HS Code for textiles?'
      }
    }

    return translations[language][key] || fallback || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
